### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by Heater711** [Fargo007/TROOPS-IN-CONTACT#1]
Hello,
have you considered to setting up SRS ?

**Comment by Fargo007** [comment]
In what regard?

**Comment by Heater711** [comment]
To give the 5 Line only in a specific radio frequency and not to all blue players

**Comment by Fargo007** [comment]
I don't believe it's possible to do that directly via SRS from lua code.

It's also unfortunately not possible with radio transmissions, because they need to be executed with logic that chooses them ato fit the random scenarios and has delays calculated based on the length of each dynamic sound file so they don't overtransmit each other.  

If we do get underlying hooks that can make that work I would be happy to take a look at it.

The next version will have the ability to silence and re-enable the voice transmissions.
